#+title: My Emacs configuration
:HEADER:
#+startup: fold hideblocks
#+property: header-args:elisp :tangle yes

# Local Variables:
# eval: (add-hook 'after-save-hook #'org-babel-tangle nil t)
# End:
:END:

Welcome to my literate Emacs configuration. It is written in org-mode as I find that it helps keeping things tidy.

* Personal information

#+begin_src elisp
  (setq user-full-name "Oskar Haukebøe"
        user-mail-address "ohaukeboe@pm.me")
#+end_src

* Initial settings
** Emacs

#+begin_src elisp
  (use-package emacs
    :hook
    (before-save . delete-trailing-whitespace)
    (prog-mode . display-line-numbers-mode)

    :bind
    ("C-=" . text-scale-increase)
    ("C--" . text-scale-decrease)
    ("C-0" . text-scale-adjust)

    :custom
    (byte-compile-warnings '(not free-vars unresolved noruntime lexical make-local))
    (warning-minimum-level :error)

    ;; UI settings
    (scroll-bar-mode nil)
    (tool-bar-mode nil)
    (menu-bar-mode nil)
    (set-fringe-mode '(8 . 0))

    ;; Add spacing between windows
    (window-divider-default-right-width 10)
    (window-divider-default-places 'right-only)


    ;; Behavior settings
    (global-auto-revert-mode t)
    (electric-pair-mode t)

    (savehist-mode t)               ; Save history accross emacs sessions
    (use-short-answers t)                       ; y/n instead of yes/no
    (word-wrap t)                               ; Wrap lines at space between words
    (truncate-lines t)                          ; Truncate lines instead of wrapping
    (initial-scratch-message nil)               ; Clean scratch buffer
    (auto-revert-interval 1)                    ; Refresh buffers every second
    (split-width-threshold 180)                  ; Split vertically by default
    (split-height-threshold nil)                ; Split vertically by default
    (use-dialog-box nil)                        ; Disable dialog boxes
    (inhibit-startup-screen t)                  ; Disable startup screen
    (recentf-max-saved-items 100)               ; Show more recent files
    (scroll-margin 1)                           ; Add margin when scrolling
    (backup-directory-alist                     ; Put backups in var/backups
     `(("." . ,(concat user-emacs-directory "var/backups"))))
    (indent-tabs-mode nil)                      ; Use spaces instead of tabs
    (tab-width 2)                               ; Set tab width to 2 spaces
    (isearch-allow-motion t)                    ; Allow movement during search
    (repeat-mode t)                             ; Enable repeat mode

    ;; Allow undo/redo window configuration with C-c <left>/<right>
    (winner-mode 1)

    :custom-face
    (default ((t :family "Roboto Mono" :height 120)))
    (fixed-pitch ((t :family "Roboto Mono" :height 0.9)))
    (variable-pitch ((t :family "Roboto Serif" :height 1.3))))
#+end_src

** Package

Most packages are available on melpa.

#+begin_src elisp
  (use-package package
    :config
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t))

#+end_src

** Benchmark
This is a handy package which helps showing what packages are slowing down the Emacs init time.

#+begin_src elisp
  (use-package benchmark-init
    :ensure t
    :init
    (benchmark-init/activate)
    ;; (add-hook 'after-init-hook 'benchmark-init/deactivate)
    :hook
    (after-init-hook .
              (lambda ()
                (run-at-time 5 nil 'benchmark-init/deactivate))))
#+end_src

* Look and feel
** Theme

#+begin_src elisp
  (use-package doom-themes
    :ensure t
    :custom-face
    (default ((t (:background "#1b1b1b"))))
    (ansi-color-bright-black ((nil (:inherit font-lock-comment-face
                                             :foreground nil
                                             :background nil))))
    :config
    (load-theme 'doom-tomorrow-night t))
#+end_src

** Nerd icons
This package provides a set of icons for Emacs.

#+begin_src elisp
  (use-package nerd-icons
    :ensure t
    :custom
    (nerd-icons-nerd-font-font-family "Symbols Nerd Font Mono")
    (nerd-icons-install-font t))
#+end_src

** Doom modeline

#+begin_src elisp
  (use-package doom-modeline
      :ensure t
      :hook (after-init . doom-modeline-mode)
      :custom
      (doom-modeline-buffer-file-name-style 'auto)
      (doom-modeline-modal nil)
      (doom-modeline-buffer-encoding nil)
      (doom-modeline-percent-position nil)
      (column-number-mode t)

      :config
      (doom-modeline-def-modeline 'main
      '(eldoc bar workspace-name window-number modals matches follow buffer-info remote-host word-count parrot selection-info)
      '(compilation objed-state misc-info persp-name battery grip irc mu4e gnus github debug repl minor-modes input-method indent-info buffer-encoding process check lsp vcs time buffer-position))

    (doom-modeline-def-modeline 'minimal
      '(bar window-number modals matches buffer-info-simple)
      '(media-info time))

    (doom-modeline-def-modeline 'special
      '(eldoc bar window-number modals matches buffer-info remote-host word-count parrot selection-info)
      '(compilation objed-state misc-info battery irc-buffers debug minor-modes input-method indent-info buffer-encoding process time buffer-position))

    (doom-modeline-def-modeline 'project
      '(bar window-number modals buffer-default-directory remote-host)
      '(compilation misc-info battery irc mu4e gnus github debug minor-modes input-method process time buffer-position))

    (doom-modeline-def-modeline 'dashboard
      '(bar window-number modals buffer-default-directory-simple remote-host)
      '(compilation misc-info battery irc mu4e gnus github debug minor-modes input-method process time))

    (doom-modeline-def-modeline 'vcs
      '(bar window-number modals matches buffer-info remote-host parrot selection-info)
      '(compilation misc-info battery irc mu4e gnus github debug minor-modes buffer-encoding process time buffer-position))

    (doom-modeline-def-modeline 'package
      '(bar window-number modals package)
      '(compilation misc-info process time))

    (doom-modeline-def-modeline 'info
      '(bar window-number modals buffer-info info-nodes parrot selection-info)
      '(compilation misc-info buffer-encoding time buffer-position))

    (doom-modeline-def-modeline 'media
      '(bar window-number modals buffer-size buffer-info)
      '(compilation misc-info media-info process vcs time))

    (doom-modeline-def-modeline 'message
      '(eldoc bar window-number modals matches buffer-info-simple word-count parrot selection-info)
      '(compilation objed-state misc-info battery debug minor-modes input-method indent-info buffer-encoding time buffer-position))

    (doom-modeline-def-modeline 'pdf
      '(bar window-number modals matches buffer-info pdf-pages)
      '(compilation misc-info process vcs time))

    (doom-modeline-def-modeline 'org-src
      '(eldoc bar window-number modals matches buffer-info word-count parrot selection-info)
      '(compilation objed-state misc-info debug minor-modes input-method indent-info buffer-encoding process check lsp time buffer-position))

    (doom-modeline-def-modeline 'helm
      '(bar helm-buffer-id helm-number helm-follow helm-prefix-argument)
      '(helm-help time))

    (doom-modeline-def-modeline 'timemachine
      '(eldoc bar window-number modals matches git-timemachine word-count parrot selection-info)
      '(misc-info minor-modes indent-info buffer-encoding time buffer-position))

    (doom-modeline-def-modeline 'calculator
      '(window-number modals matches calc)
      '(misc-info minor-modes process buffer-position)))
#+end_src

** Dashboard
A prettier startup screen

#+begin_src elisp
  (use-package dashboard
    :ensure t
    ;; :hook
    ;; ('elpaca-after-init-hook #'dashboard-insert-startupify-lists)
    ;; ('elpaca-after-init-hook #'dashboard-initialize)

    :custom
    ;; (dashboard-projects-backend 'projectile)
    (dashboard-set-heading-icons t)
    (dashboard-set-file-icons t)
    (dashboard-display-icons-p t)     ; display icons on both GUI and terminal
    (dashboard-icon-type 'nerd-icons) ; use `nerd-icons' package
    (dashboard-week-agenda nil)       ; nil for only current day
    ;;                                   ; and t for the whole week
    (dashboard-center-content t)
    ;; ;; (dashboard-startup-banner 2)
    (dashboard-items '((recents  . 5)
                       (bookmarks . 5)
                       (projects . 5)
                       (agenda . 5)
                       (registers . 5)))

    :config
    (dashboard-setup-startup-hook))
#+end_src

** Which-key
=which-key= is a package that displays the keybindings available after a prefix key. It is very useful to discover new keybindings.

#+begin_src elisp
  (use-package which-key
    :ensure t
    :config
    (which-key-mode))
#+end_src

* Completion and navigation
** Corfu
Corfu is a completion framework that provides a horizontal completion UI. It is a very simple package that does not provide any completion backends.

#+begin_src elisp
  (use-package corfu
    :ensure t
    :custom
    ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-auto t)                 ;; Enable auto completion
    ;; (corfu-separator ?\s)          ;; Orderless field separator
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
    ;; (corfu-scroll-margin 5)        ;; Use scroll margin

    :config
    (global-corfu-mode))
#+end_src

It is also possible to use Corfu in the terminal. This requires the =corfu-terminal= package to be installed.

#+begin_src elisp
  (use-package corfu-terminal
    :ensure t
    :after corfu
    :config
    (unless (display-graphic-p)
      (corfu-terminal-mode +1)))
#+end_src

Make Corfu sort by last selected candidates.

#+begin_src elisp
  (use-package corfu-history
    :after corfu
    :config
    (corfu-history-mode t))
#+end_src

Make Corfu also show up in the minibuffer.

#+begin_src elisp
  (with-eval-after-load 'corfu
    (defun oh/corfu-enable-always-in-minibuffer ()
      "Enable Corfu in the minibuffer if Vertico/Mct are not active."
      (unless (or (bound-and-true-p mct--active)
                  (bound-and-true-p vertico--input)
                  (eq (current-local-map) read-passwd-map))
        (setq-local corfu-echo-delay nil ; Disable automatic echo
                    corfu-popupinfo-delay 0.0)
        (corfu-mode 1)))

    (add-hook 'minibuffer-setup-hook #'oh/corfu-enable-always-in-minibuffer))
#+end_src

** Vertico
Vertico is a completion framework that provides a vertical completion UI. It is a very simple package that does not provide any completion backends. It is meant to be used with =orderless=.

#+begin_src elisp
  ;; Enable vertico
  (use-package vertico
    :ensure t
    :custom
    ;; Enable recursive minibuffers
    (enable-recursive-minibuffers t)
    :config
    (vertico-mode))

    ;; Different scroll margin
    ;; (setq vertico-scroll-margin 0)

    ;; Show more candidates
    ;; (setq vertico-count 20))

    ;; Grow and shrink the Vertico minibuffer
    ;; (setq vertico-resize t)

    ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
    ;; (setq vertico-cycle t)
#+end_src

Allow using different vertico configurations for different prompts.

#+begin_src elisp
  (use-package vertico-multiform
    :after vertico)
#+end_src

Allow displaying the vertico completions in a grid

#+begin_src elisp
  (use-package vertico-grid
    :after vertico)
#+end_src

** Orderless
Orderless is a completion style that allows matching candidates in any order. It is very useful to find candidates when you don't remember the exact order of the characters.

#+begin_src elisp
  (use-package orderless
    :ensure t
    :after vertico
    ;; :init
    ;; Configure a custom style dispatcher (see the Consult wiki)
    ;; (setq orderless-style-dispatchers '(+orderless-consult-dispatch orderless-affix-dispatch)
    ;;       orderless-component-separator #'orderless-escapable-split-on-space)
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** Marginalia
Marginalia is a package that displays additional information about the candidates in the minibuffer. It is very useful to find the right candidate.

#+begin_src elisp
  (use-package marginalia
    :ensure t
    :after vertico
    ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
    ;; available in the *Completions* buffer, add it to the
    ;; `completion-list-mode-map'.
    :bind (:map minibuffer-local-map
           ("M-A" . marginalia-cycle))

    :config
    (marginalia-mode))
#+end_src

It's also nice to have some nice looking icons for the completion candidates. This requires the =nerd-fonts= package to be installed.

#+begin_src elisp
  (use-package nerd-icons-completion
    :ensure t
    ;; :after marginalia
    :hook
    (marginalia-mode . nerd-icons-completion-marginalia-setup)
    :config
    (nerd-icons-completion-mode))
#+end_src

** Consult
Consult is a package that provides a set of commands for searching and navigating. It is very useful to find files, buffers, etc.

#+begin_src elisp
  (use-package consult
    :ensure t
    :custom
    (consult-buffer-sources
     '(consult--source-hidden-buffer
       consult--source-modified-buffer
       consult--source-buffer
       ;; +consult-source-special
       consult--source-recent-file
       consult--source-file-register
       consult--source-bookmark
       consult--source-project-buffer-hidden
       consult--source-project-recent-file-hidden))

    :bind
    (;; C-c bindings in `mode-specific-map'
     ("C-c M-x" . consult-mode-command)
     ("C-c h" . consult-history)
     ("C-c k" . consult-kmacro)
     ("C-c m" . consult-man)
     ("C-c i" . consult-info)
     ([remap Info-search] . consult-info)
     ;; C-x bindings in `ctl-x-map'
     ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
     ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
     ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
     ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
     ;; ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
     ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
     ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
     ;; Other custom bindings
     ("M-y" . consult-yank-pop)                ;; orig. yank-pop
                                          ; M-g bindings in `goto-map'
     ("M-g e" . consult-compile-error)
     ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
     ("M-g g" . consult-goto-line)             ;; orig. goto-line
     ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
     ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
     ("M-g m" . consult-mark)
     ("M-g k" . consult-global-mark)
     ("M-g i" . consult-imenu)
     ("M-g I" . consult-imenu-multi)
     ;; M-s bindings in `search-map'
     ("M-s d" . consult-find)                  ;; Alternative: consult-fd
     ("M-s c" . consult-locate)
     ("M-s g" . consult-grep)
     ("M-s G" . consult-git-grep)
     ("M-s r" . consult-ripgrep)
     ("M-s l" . consult-line)
     ("M-s L" . consult-line-multi)
     ("M-s k" . consult-keep-lines)
     ("M-s u" . consult-focus-lines)
     ;; Isearch integration
     ("M-s e" . consult-isearch-history)
     :map isearch-mode-map
     ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
     ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
     ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
     ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
     ;; Minibuffer history
     :map minibuffer-local-map
     ("M-s" . consult-history)                 ;; orig. next-matching-history-element
     ("M-r" . consult-history))                ;; orig. previous-matching-history-element

    :config
    (recentf-mode 1))

    ;; (defvar +consult-special-filter "\\`\\*.*\\*\\'")
    ;; (defvar +consult-source-special
    ;;   `(:name      "Special"
    ;;     :narrow    ?x
    ;;     ;; :hidden t
    ;;     :category  buffer
    ;;     :face      consult-buffer
    ;;     :history   buffer-name-history
    ;;     ;; Specify either :action or :state
    ;;     ;; :action    ,#'consult--buffer-action ;; No preview
    ;;     :state  ,#'consult--buffer-state  ;; Preview
    ;;     :items
    ;;     ,(lambda () (consult--buffer-query
    ;;                  :sort 'visibility
    ;;                  :as #'buffer-name
    ;;                  :exclude (remq +consult-special-filter consult-buffer-filter)
    ;;                  ;; :include '(+consult-special-filter)
    ;;                  :mode 'special-mode)))
    ;;   "special buffer source.")

    ;; (add-to-list 'consult-buffer-filter +consult-special-filter))

#+end_src

* Project management
** Magit

#+begin_src elisp
  (use-package magit
    :ensure t
    :defer t
    :custom
    (magit-display-buffer-function
     #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

Magit-todos for integrating TODO keywords with magit's overview screen

#+begin_src elisp
  (use-package magit-todos
    :ensure t
    ;; :ensure nil
    ;; :elpaca (magit-todos :type git :host github :repo "alphapapa/magit-todos")
    :after magit
    :config
    (magit-todos-mode 1))

  (use-package hl-todo
    :ensure t
    :config
    (global-hl-todo-mode 1))
#+end_src

** diff-hl

#+begin_src elisp
  (use-package diff-hl
    :ensure t
    :hook
    (prog-mode . diff-hl-mode)
    (dired-mode . diff-hl-dired-mode)
    :custom
    (diff-hl-flydiff-mode t)
    (diff-hl-flydiff-delay 0)
    (diff-hl-update-async t)
    (diff-hl-dired-extra-indicators nil))
#+end_src

** Forge
Make magit integrate with github and other git hosting services.

#+begin_src elisp
  (use-package forge
    :ensure t
    :after magit
    :custom
    (forge-add-default-bindings nil)
    (auth-sources '("~/.authinfo")))
#+end_src

* Programming
** Eglot
Eglot is a client for Language Server Protocol (LSP). It is a protocol that allows for IDE-like features such as code completion, code navigation, etc. It is supported by many programming languages.

For information about setting up a new lsp server, see [[https://joaotavora.github.io/eglot/][Link]].

#+begin_src elisp
  ;; (use-package eglot
  ;;   ;; :hook (prog-mode . eglot-ensure)
  ;;   :general
  ;;   (oh/leader-key eglot-mode-map
  ;;    "ca" '(eglot-code-actions :wk "code actions")
  ;;    "cr" '(eglot-rename :wk "rename")
  ;;    "cf" '(eglot-format :wk "format")
  ;;    "cm" '(consult-imenu :wk "navigate symbols")
  ;;    "cM" '(consult-imenu-multi :wk "navigate symbols (multi)")
  ;;    "cd" '(consult-lsp-diagnostics :wk "diagnostics")))


  ;; (use-package eglot-x
  ;;   :ensure (eglot-x :type git :host github :repo "nemethf/eglot-x")
  ;;   :disabled
  ;;   :demand
  ;;   :after eglot
  ;;   :config
  ;;   (eglot-x-setup))
#+end_src

** Eldoc
Eldoc is a minor mode that shows documentation in the echo area. It is enabled by default in =prog-mode=.

#+begin_src elisp
  (use-package eldoc
    :defer t
    :custom
    (eldoc-echo-area-use-multiline-p nil)
    (eldoc-idle-delay 0)
    :config
    (global-eldoc-mode -1))
#+end_src

** Flymake
Flymake is a minor mode that performs on-the-fly syntax checking. It is enabled by default in =prog-mode=.

#+begin_src elisp
  (use-package flymake
    :after prog-mode
    :custom
    (flymake-show-diagnostics-at-end-of-line t))
#+end_src

** Rainbow mode
Visualize the colors of color codes

#+begin_src elisp
  (use-package rainbow-mode
    :ensure t
    :hook prog-mode)
#+end_src

** Editorconfig

#+begin_src elisp
  (use-package editorconfig
    :ensure t
    :after prog-mode
    :config
    (editorconfig-mode 1))
#+end_src

* Languages
Emacs 29 has built-in support for =tree-sitter=, which is a parser generator tool and an incremental parsing library. It is used to create a syntax highlighting engine that is faster and more accurate than the built-in one. However, Emacs does not ship with any language support for =tree-sitter=, so we'll have to install it ourselves... or have =treesit-auto= to do it for us.

According to the =treesit-auto= documentation, Emacs 30 will ship with better defaults for =tree-sitter=, so hopefully we won't need =treesit-auto= anymore.

#+begin_src elisp
  (use-package treesit-auto
    :ensure t
    :disabled
    :after prog-mode
    :custom
    (treesit-auto-install 'prompt)
    :config
    (treesit-auto-add-to-auto-mode-alist 'all)
    (delete 'c-sharp treesit-auto-langs)
    (global-treesit-auto-mode))
#+end_src

** Rust

#+begin_src elisp
  (use-package rust-mode
    :ensure t
    :hook (rust-ts-mode . eglot-ensure)
    :mode "\\.rs\\'"
    :bind
    ("C-c C-c C-r" . rust-run)
    ("C-c C-c C-c" . rust-run-clippy)
    ("C-c C-c C-t" . rust-test)
    ("C-c C-c C-k" . rust-check)
    :custom
    (rust-mode-treesitter-derive t)
    :config
    (with-eval-after-load 'eglot
      (add-to-list 'eglot-server-programs
                   '((rust-ts-mode rust-mode) .
                     ("rust-analyzer" :initializationOptions (:check (:command "clippy")))))))
#+end_src

** C

#+begin_src elisp
  (use-package c-ts-mode
    :hook (c-ts-mode . eglot-ensure)
    :mode
    "\\.c\\'"
    "\\.h\\'")

#+end_src

** Typescript

#+begin_src elisp
  (use-package typescript-ts-mode
    :hook (typescript-ts-mode . eglot-ensure)
    :mode "\\.ts\\'")
#+end_src

For editing =.tsx= files, we'll use =jtsx=.

#+begin_src elisp
  (use-package jtsx
    :ensure t
    :mode (("\\.jsx?\\'" . jtsx-jsx-mode)
           ("\\.tsx?\\'" . jtsx-tsx-mode))
    :commands jtsx-install-treesit-language
    :hook ((jtsx-jsx-mode . hs-minor-mode)
           (jtsx-tsx-mode . hs-minor-mode)
           (jtsx-jsx-mode . eglot-ensure)
           (jtsx-tsx-mode . eglot-ensure)))
#+end_src

** C#
When in a C# project, it is important to set the variable =lsp-csharp-solution-file= to point to the project solution file (.sln). It is recommended to set this in a =.dir-locals.el= file for the project.

#+begin_src elisp
  (use-package csharp-mode
       ;; :hook (csharp-ts-mode . lsp)
    :hook (csharp-mode . eglot-ensure)
    :mode "\\.cs\\'"
    ;; (add-to-list 'treesit-language-source-alist
    ;;              '(csharp . ("https://github.com/tree-sitter/tree-sitter-c-sharp" Latest)))
    :config
    ;; (add-to-list 'treesit-language-source-alist
    ;;              '(csharp . "https://github.com/tree-sitter/tree-sitter-c-sharp"))
    (with-eval-after-load 'eglot
      (add-to-list 'eglot-server-programs
                   '(csharp-mode . ("OmniSharp" "-lsp")))))

    ;; :general
    ;; (:keymaps 'csharp-ts-mode-map
    ;;           :states 'normal
    ;;           "K" 'lsp-describe-thing-at-point))
#+end_src

** dotnet

#+begin_src elisp
  (use-package sharper
    ;; :disabled)
    :ensure t
    :after '(csharp-mode csharp-ts-mode))
    ;; :general
    ;; (oh/leader-key csharp-ts-mode-map
    ;;   "m d" 'sharper-main-transient))
#+end_src

** Json

#+begin_src elisp
  (use-package json-ts-mode
    :hook (json-ts-mode . eglot-ensure)
    :mode "\\.json\\'")
#+end_src

** Python

#+begin_src elisp
  (use-package python-ts-mode
    :hook (python-ts-mode . eglot-ensure)
    ;; :hook (python-ts-mode . lsp)
    :mode "\\.py\\'")
    ;; :general)
    ;; (:keymaps 'python-ts-mode-map
    ;;  :states '(normal visual)
    ;;  "K" 'lsp-describe-thing-at-point))

    ;; :config
    ;; (lsp-register-custom-settings
    ;;  '(("pyls.plugins.pyls_mypy.enabled" t t)
    ;;    ("pyls.plugins.pyls_mypy.live_mode" nil t)))
    ;;    ;; ("pyls.plugins.pyls_black.enabled" t t)
    ;;    ;; ("pyls.plugins.pyls_isort.enabled" t t)))

    ;; :custom
    ;; (lsp-pylsp-plugins-yapf-enabled t)
    ;; (lsp-pylsp-plugins-flake8-enabled nil))
    ;; (lsp-pylsp-plugins-flake8-max-line-length 80)
    ;; (lsp-pylsp-plugins-pycodestyle-max-line-length 80))
#+end_src

** Elisp

#+begin_src elisp
  (use-package parinfer-rust-mode
    :disabled
    ;; :hook
    ;; (emacs-lisp-mode . parinfer-rust-mode)
    ;; (emacs-lisp-mode . (lambda ()
    ;;                     (electric-pair-local-mode -1)
    ;;                     (parinfer-rust-mode 1)))

    :custom
    (parinfer-rust-auto-download t))
    ;; :config
    ;; (add-to-list 'oh/electric-pair-mode-blacklist-modes 'parinfer-rust-mode))

#+end_src

** Nix

#+begin_src elisp
  (use-package nix-mode
      ;; :hook (nix-mode . eglot-ensure)
    :mode "\\.nix\\'")
#+end_src

** LaTex

#+begin_src elisp
  (use-package TeX-latex-mode
    :mode ("\\.tex\\'" . TeX-latex-mode)
    :hook
    (TeX-mode . eglot-ensure)
    (TeX-mode . (lambda () (auto-fill-mode)))
    (TeX-mode . (lambda () (truncate-lines nil)))
    (TeX-mode . (lambda () (reftex-mode 1)))
    :custom
    (LaTeX-electric-left-right-brace t)
    (TeX-view-program-selection '((output-pdf "PDF Tools")))
    (TeX-source-correlate-start-server t)
    (TeX-auto-save t)
    (TeX-parse-self t)
    (TeX-master nil)
    :config
    ;; (load "auctex.el" nil t t)
    ;; Use pdf-tools to open PDF files

    ;; Update PDF buffers after successful LaTeX runs
    (add-hook 'TeX-after-compilation-finished-functions
               #'TeX-revert-document-buffer))
#+end_src

CDLatex makes writing math a pleasure.

#+begin_src elisp
  (use-package cdlatex
    :hook (LaTeX-mode . cdlatex-mode))
#+end_src

** Dot

#+begin_src elisp
  (use-package graphviz-dot-mode
    :ensure t
    :mode "\\.dot\\'"
    :custom
    (graphviz-dot-indent-width 4))
#+end_src

** PlantUML

#+begin_src elisp
  (use-package plantuml-mode
    :ensure t
    :mode
    ("\\.plantuml\\'" . plantuml-mode)
    ("\\.puml\\'" . plantuml-mode)
    :init
    (with-eval-after-load 'org
      (add-to-list 'org-src-lang-modes
                   '("plantuml" . plantuml))
      (add-to-list 'org-babel-load-languages
                   '(plantuml . t)))

    :custom
    (plantuml-default-exec-mode 'executable)
    (org-plantuml-exec-mode 'plantuml)
    (plantuml-indent-level 4)
    (plantuml-output-type "png"))
#+end_src

** biblatex

#+begin_src elisp
  (use-package bibtex
    :hook (bibtex-mode . eglot-ensure))
    ;; :general
    ;; (oh/leader-key bibtex-mode-map
    ;;   "mri" '(citar-insert-bibtex :wk "Insert bibtex")))
#+end_src

* Biblio
To manage my bibliography entries, I use [[https:zotero.org/][zotero]] which allows me to easily use their browser extension to add the bibliography entries to the database. It also automatically downloads the PDF, belonging to the entry. I also use [[https://github.com/jlegewie/zotfile][zotfile]] to automatically rename the downloaded PDFs, and to place them in the ~library-path~ which is in a cloud folder and which =citar= can look through to find the files belonging to the bibliography entries. I also use [[https://github.com/retorquere/zotero-better-bibtex][better-bibtex]] which automatically exports my bibliography to a BibLatex file every time the bibliography is updated, which =citar= then looks through. =better-bibtex= also takes care of the cite-keys, which allows me to set the naming scheme in =zotfile= to ~{%b}~ which makes it use the cite-key as filename. This step is crucial, as =citar= finds the matching file for an entry, by matching the filename with the cite-key.

Some other zotero plugins I use are:
- [[https://github.com/scitedotai/scite-zotero-plugin/][scite]] is also a very nice site, for finding relevant papers as well as to check how trustworthy an article is. Its =zotero= plugin makes it easy to get this information for your entire bibliography database.
- [[https://github.com/PubPeerFoundation/pubpeer_zotero_plugin][PubPeer]] which is a cite for sharing comments about publications.

#+begin_src elisp
  (defvar oh/bib-files
     '("~/Nextcloud/.org/references.bib"
       "~/Nextcloud/.org/bibliography/zotero.bib"
       "~/Nextcloud/.org/bibliography/uni/IN3000.bib"
       "~/Nextcloud/.org/bibliography/uni/IN2000 gang.bib"
       "~/Nextcloud/.org/bibliography/uni/IN2120_gang-midterm.bib"))

  (defvar oh/roam-dir
    "~/Nextcloud/org_notes/roam/bibliography/")

  (defvar oh/library-dir
    "~/Nextcloud/.org/library/")
#+end_src

** org-cite

#+begin_src elisp
  (use-package oc
    :after org
    :custom
    (org-cite-csl-styles-dir "~/Zotero/styles")
    (org-cite-global-bibliography oh/bib-files)
    (org-cite-export-processors
     '((t csl))))
       ;; (latex biblatex))))
#+end_src

** citar

#+begin_src elisp
  (use-package citar
    :ensure t
    :hook
    (org-mode . citar-capf-setup)
    (latex-mode . citar-capf-setup)
    ;; :general
    ;; (oh/leader-key '(org-mode-map LaTeX-mode-map)
    ;;   "mr" '(:ignore t :which-key "references")
    ;;   "mrc" '(citar-insert-citation :which-key "insert citation")
    ;;   "mre" '(citar-export-local-bib-file :which-key "export local bib file"))

    ;; (oh/leader-key
    ;;   "nr" '(:ignore t :wk "references")
    ;;   "nro" '(citar-open :wk "open resource"))

    :custom
    (citar-citeproc-csl-styles-dir "~/Zotero/styles/")
    (citar-citeproc-csl-style "apa.csl")
    (bibtex-dialect 'biblatex)
    (citar-bibliography oh/bib-files)
    (citar-notes-paths (list oh/roam-dir))          ; List of directories for reference nodes
    (citar-open-note-function 'orb-citar-edit-note) ; Open notes in `org-roam'
    ;; (citar-at-point-function 'embark-act)           ; Use `embark'
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar)

    :config
    (defvar citar-indicator-files-icons
      (citar-indicator-create
       :symbol (nerd-icons-faicon
                "nf-fa-file_o"
                :face 'nerd-icons-green
                :v-adjust -0.1)
       :function #'citar-has-files
       :padding "  " ; need this because the default padding is too low for these icons
       :tag "has:files"))
    (defvar citar-indicator-links-icons
      (citar-indicator-create
       :symbol (nerd-icons-codicon
                "nf-cod-link"
                :face 'nerd-icons-orange
                :v-adjust 0.01)
       :function #'citar-has-links
       :padding "  "
       :tag "has:links"))
    (defvar citar-indicator-notes-icons
      (citar-indicator-create
       :symbol (nerd-icons-codicon
                "nf-cod-note"
                :face 'nerd-icons-blue
                :v-adjust -0.3)
       :function #'citar-has-notes
       :padding "    "
       :tag "has:notes"))
    (defvar citar-indicator-cited-icons
      (citar-indicator-create
       :symbol (nerd-icons-faicon
                "nf-fa-circle_o"
                :face 'nerd-icon-green)
       :function #'citar-is-cited
       :padding "  "
       :tag "is:cited"))

    (setq citar-indicators
      (list citar-indicator-files-icons
            citar-indicator-links-icons
            citar-indicator-notes-icons
            citar-indicator-cited-icons)))

  ;; (use-package citar-embark
  ;;   :ensure t
  ;;   :after citar
  ;;   :no-require
  ;;   :config (citar-embark-mode))

  (use-package citar-org
    :after (oc citar)
    :custom
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar))
#+end_src

** citar-org-roam

#+begin_src elisp
  (use-package citar-org-roam
    :ensure t
    :after (citar org-roam)
    :config (citar-org-roam-mode)
    ;; :general
    ;; (oh/leader-key
    ;;   "nrc" '(citar-org-roam-ref-add :wk "add ref"))
    :custom
    (citar-org-roam-capture-template-key "n")
    :config
    (add-to-list 'org-roam-capture-templates
       '("n" "literature note" plain
               "%?"
               :target
               (file+head
                "%(expand-file-name (or citar-org-roam-subdir \"\") org-roam-directory)/${citar-citekey}.org"
                "#+title: ${citar-citekey} (${citar-date}). ${note-title}.\n#+created: %U\n#+last_modified: %U\n\n")
               :unnarrowed t)))
#+end_src

* Major Modes
** Special
A special major mode is intended to view specially formatted data
rather than files.  These modes usually use read-only buffers.

#+begin_src elisp
  (use-package special
    :hook (special-mode . visual-line-mode))
#+end_src

** Org-mode
*** Org

#+begin_src elisp
  (use-package org
    :hook
    (org-mode . variable-pitch-mode)
    (org-mode . (lambda () (visual-line-mode 1)))

    :custom
    (org-export-with-smart-quotes t)
    (org-hide-emphasis-markers t)		; Hide markup characters
    (org-startup-indented t)
    (org-pretty-entities t)
    (org-use-sub-superscripts "{}")
    (org-hide-emphasis-markers t)
    (org-startup-with-inline-images t)
    (org-image-actual-width '(300))
    (org-auto-align-tags nil)
    (org-tags-column 0)
    (org-fold-catch-invisible-edits 'show)
    (org-elipsis "…")
    (org-default-notes-file "~/Nextcloud/org_notes/notes.org")
    (org-agenda-files `(,org-default-notes-file))

    :config
    ;; Pretty bullets
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
    (add-to-list 'org-latex-packages-alist '("" "listings"))
    (with-eval-after-load 'ox-latex
      (setq org-latex-listings 'listings)
      (setq org-latex-listings-options
            '(("basicstyle" "\\ttfamily\\footnotesize")
              ("breaklines" "true")
              ("showstringspaces" "false")
              ("postbreak" "\\mbox{$\\hookrightarrow$\\space}")
              ("xleftmargin" "2.8em")
              ("framexleftmargin" "2.8em")
              ("numbers" "left")
              ("tabsize" "2"))))

    :custom-face
    (org-level-1 ((t (:inherit outline-1 :height 1.5))))
    (org-level-2 ((t (:inherit outline-2 :height 1.3))))
    (org-level-3 ((t (:inherit outline-3 :height 1.2))))
    (org-level-4 ((t (:inherit outline-4 :height 1.1))))
    (org-level-5 ((t (:inherit outline-5 :height 1.0))))
    (org-level-6 ((t (:inherit outline-6 :height 1.0))))
    (org-level-7 ((t (:inherit outline-7 :height 1.0))))
    (org-level-8 ((t (:inherit outline-8 :height 1.0))))

    (org-block ((t (:inherit fixed-pitch))))
    (org-code ((t (:inherit (shadow fixed-pitch)))))

    (org-table ((t (:inherit fixed-pitch)))))
#+end_src

*** Org-appear
Toggle the visibility of emphasis markers when the cursor is on the line.

#+begin_src elisp
  (use-package org-appear
    :ensure t
    :hook (org-mode . org-appear-mode))
#+end_src

*** org-fragtog
Automatically toggle =org-preview-latex-fragment= when the cursor is on the line.

#+begin_src elisp
  (use-package org-fragtog
    :ensure t
    :hook (org-mode . org-fragtog-mode))
#+end_src

*** Org-modern
Provides a clean look for org-mode.

#+begin_src elisp
  (use-package org-modern
    :ensure t
    :hook (org-mode . org-modern-mode)
    :custom
    (org-modern-table nil))
#+end_src

*** src-block completion

#+begin_src elisp
  (use-package org-block-capf
    :vc (:url "https://github.com/xenodium/org-block-capf")
    :custom
    (org-block-capf-explicit-lang-defaults nil)
    :hook (org-mode . org-block-capf-add-to-completion-at-point-functions))
#+end_src

*** PDF preview
Show pdf previews as inline images.

#+begin_src elisp
  (use-package org-inline-pdf
    :ensure t
    :hook (org-mode . org-inline-pdf-mode))
#+end_src

*** Download

#+begin_src elisp
  (use-package org-download
    :ensure t
    :after org
    :custom
    (org-download-method 'attach))
    ;; :general
    ;; (oh/leader-key org-mode-map
    ;;   "map" 'org-download-clipboard
    ;;   "maf" 'org-download-screenshot
    ;;   "mar" 'org-download-rename-at-point))
#+end_src

*** Present
It is nice sometimes to use org for presentations.

#+begin_src elisp
  (use-package org-present
    :ensure t
    :after org
    ;; :general
    ;; (oh/leader-key 'org-mode-map
    ;;   "tp" '(org-present :wk "present"))
    :custom
    (org-present-text-scale 2)
    (org-present-startup-folded t)
    :config
    (add-hook 'org-present-mode-hook
              (lambda ()
                ;; (focus-mode t)
                (org-present-big)
                (org-appear-mode -1)
                (org-present-read-only)
                (setq header-line-format " ")))
    (add-hook 'org-present-mode-quit-hook
              (lambda ()
                ;; (focus-mode -1)
                (org-present-small)
                (org-appear-mode t)
                (org-present-read-write)
                (setq header-line-format nil)
                (nano-modeline-org-mode))))
#+end_src

*** oc-pandoc
Export dispatcher using pandoc

#+begin_src elisp
  (use-package ox-pandoc
    :ensure t
    :after ox)
#+end_src

*** org-roam

#+begin_src elisp
  (use-package org-roam
    :ensure t
    :defer
    :custom
    (org-roam-completion-everywhere t)
    ;; (org-roam-node-display-template "${title:*} ${tags:10}")
    (org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
    (org-roam-directory (file-truename "~/Nextcloud/org_notes/roam"))
    (org-roam-dailies-directory (file-truename "~/Nextcloud/org_notes/daily"))
    ;; :general
    ;; (oh/leader-key
    ;;   "nf" '(org-roam-node-find :wk "find")
    ;;   "nc" '(org-roam-capture :wk "capture")
    ;;   "ni" '(org-roam-node-insert :wk "insert")
    ;;   "nb" '(org-roam-buffer-toggle :wk "buffer")
    ;;   "nt" '(org-roam-tag-add :wk "add tag")
    ;;   "nl" '(consult-org-roam-backlinks :wk "backlinks")
    ;;   "nrr" '(org-roam-ref-find :wk "find ref")
    ;;   "nR" '(org-roam-refile :wk "refile")
    ;;   "na" '(org-roam-alias-add :wk "add alias"))

    :config
    (org-roam-db-autosync-mode 1))
#+end_src

*** org-roam-ui

#+begin_src elisp
  (use-package org-roam-ui
    :ensure t
    :disabled
    ;; :after org-roam
    ;;         normally we'd recommend hooking orui after org-roam, but since
    ;;         org-roam does not have a hookable mode anymore, you're advised to
    ;;         pick something yourself if you don't care about startup time, use
    ;;  :hook (after-init . org-roam-ui-mode)
    ;; :general
    ;; (oh/leader-key
    ;;   "ng" '(org-roam-ui-mode :which-key "org-roam-ui"))
    :custom
    (org-roam-ui-sync-theme t)
    (org-roam-ui-follow t)
    (org-roam-ui-update-on-save t)
    (org-roam-ui-open-on-start t))

#+end_src

*** consult-org-roam

#+begin_src elisp
  (use-package consult-org-roam
    :ensure t
    :after org-roam
    :custom
    (consult-org-roam-mode 1)
    ;; Use `ripgrep' for searching with `consult-org-roam-search'
    (consult-org-roam-grep-func #'consult-ripgrep)
    ;; Configure a custom narrow key for `consult-buffer'
    (consult-org-roam-buffer-narrow-key ?r)
    ;; Display org-roam buffers right after non-org-roam buffers
    ;; in consult-buffer (and not down at the bottom)
    (consult-org-roam-buffer-after-buffers t)
    :config
    ;; Eventually suppress previewing for certain functions
    (consult-customize
     consult-org-roam-forward-links
     :preview-key "M-."))
     ;; :bind)
     ;; Define some convenient keybindings as an addition
     ;; ("C-c n e" . consult-org-roam-file-find)
     ;; ("C-c n b" . consult-org-roam-backlinks)
     ;; ("C-c n l" . consult-org-roam-forward-links)
     ;; ("C-c n r" . consult-org-roam-search))
#+end_src

*** org-noter

#+begin_src elisp
  (use-package org-noter
    :ensure t
    :defer
    ;; :general
    ;; (oh/leader-key
    ;;   "ne" '(org-noter :which-key "org-noter"))
    ;; ('(normal visual insert emacs)
    ;;   'org-noter-doc-mode-map
    ;;  "i" '(org-noter-insert-note :which-key "insert note"))
    :custom
    (org-noter-auto-save-last-location t)
    (org-noter-notes-search-path
     '("~/Nextcloud/org_notes" "~/Nextcloud/org_notes/roam/bibliography")))
#+end_src

** Markdown

#+begin_src elisp
  (use-package markdown-mode
    :mode "\\.md\\'"
    ;; :hook (markdown-mode . olivetti-mode)
    :custom
    (markdown-hide-markup t))
#+end_src

** Dired

#+begin_src elisp
  (use-package dired
    :commands (dired dired-jump)

    :custom
    (dired-listing-switches "-agohv --group-directories-first")
    (dired-kill-when-opening-new-dired-buffer t)
    (dired-async-mode t))

    ;; :general
    ;; (oh/leader-key
    ;;   "fd" '(dired-jump :which-key "dired jump")
    ;;   "fD" '(dired-jump-other-window :which-key "dired"))

    ;; ('normal 'dired-mode-map
    ;;   "h" 'dired-up-directory
    ;;   "l" 'dired-find-file))
#+end_src

** Eww
The emacs web browser

#+begin_src elisp
  (use-package eww
   :commands (oh/switch-to-eww-buffer)
   ;; :custom
   ;; (shr-use-fonts nil)
   ;; :general
   ;; (oh/leader-key
   ;;   "ow" '(oh/switch-to-eww-buffer :wk "eww"))

   :config
   (defun oh/switch-to-eww-buffer ()
     "Switches to an existing EWW buffer, if one exists."
     (interactive)
     (let ((eww-buf (catch 'found
                      (dolist (buf (buffer-list))
                        (when (with-current-buffer buf
                                (eq major-mode 'eww-mode))
                          (throw 'found buf))))))
       (if eww-buf
           (switch-to-buffer eww-buf)
         (call-interactively 'eww)))))
#+end_src

** Eat
A terminal emulator

#+begin_src elisp
  (use-package eat
    :ensure t
    :bind
    ("C-c e" . eat)
    :hook
    (eat-mode . (lambda () (display-line-numbers-mode -1))))
#+end_src

** Direnv
Integrate [[https://direnv.net/][direnv]] in emacs.

#+begin_src elisp
  ;; (use-package direnv
  ;;  :init
  ;;  (direnv-mode))
  (use-package direnv
    :ensure t
    :after (prog-mode)
    :config
    (direnv-mode))
#+end_src

** PDF

#+begin_src elisp
  (use-package pdf-tools
    :mode ("\\.pdf\\'" . pdf-view-mode)
    ;; :requires pdf-outline
    :commands (pdf-view-mode)
    ;:hook
    ;(pdf-view-mode-hook . evil-normal-state)
    :config
    (require 'pdf-outline))
    ;; (pdf-tools-install))
#+end_src

* Misc
** Wakatime
Wakatime is a service that tracks your coding activity. It is very useful to see how much time you spend on a project.

I've encountered issues with the =wakatime-cli= program not functioning properly. As a result, I've discovered that the most dependable method to install Wakatime is by using the Wakatime VS Code extension and simply directing it to the binary installed by VS Code.

#+begin_src elisp
  (use-package wakatime-mode
    :ensure t
    :custom
    (wakatime-disable-on-error t)
    (wakatime-cli-path "~/.wakatime/wakatime-cli")
    :config
    (global-wakatime-mode))
#+end_src

** Make

#+begin_src elisp
  (use-package makefile-executor
    :ensure t
    :hook
    ('makefile-mode-hook 'makefile-executor-mode))
    ;; :general
    ;; (oh/leader-key
    ;;   "cb" '(makefile-executor-execute-project-target :wk "Run make command")))
#+end_src

** Copilot

#+begin_src elisp
  (use-package copilot
    :hook (prog-mode . copilot-mode)
    :vc (:url "https://github.com/copilot-emacs/copilot.el")
    ;; :general
    ;; (oh/leader-key
    ;;   "ta" '(oh/toggle-copilot-mode :wk "copilot"))
    :bind (:map copilot-completion-map
                ("<tab>" . 'copilot-accept-completion)
                ("TAB" . 'copilot-accept-completion)
                ("C-TAB" . 'copilot-accept-completion-by-word)
                ("C-<tab>" . 'copilot-accept-completion-by-word)))

  ;; (defvar oh/electric-pair-mode-blacklist-modes '()
  ;;   "Modes where electric-pair-mode should not be enabled")


  ;; (defun oh/toggle-copilot-mode ()
  ;;   "Toggle copilot mode."
  ;;   (interactive)
  ;;   (if (bound-and-true-p copilot-mode)
  ;;       (progn (copilot-mode -1)
  ;;              (if (not (cl-some (lambda (mode)
  ;;                                  (derived-mode-p mode))
  ;;                                oh/electric-pair-mode-blacklist-modes))
  ;;                  (electric-pair-mode 1)))
  ;;      (progn (copilot-mode 1)
  ;;              (electric-pair-mode -1))))
#+end_src

** gptel
Use any LLM in Emacs.

#+begin_src elisp
  (use-package gptel
    :disabled
    :custom
    ;; (gptel-api-key
    ;;  (lambda () (auth-source-pass-get 'secret "openai-key")))
    (gptel-api-key
          (auth-source-pick-first-password :host "api.openai.com"))

    (gptel-model "gpt-4-1106-preview"))
    ;; :general
    ;; (oh/leader-key
    ;;   "ogg" '(gptel :wk "gptel")
    ;;   "ogm" '(gptel-menu :wk "gptel menu")))
#+end_src

** SICP
Of course I need to have the wizard book as info pages :)

#+begin_src elisp
  (use-package sicp
    :ensure t
    :after info)
#+end_src

** Mail
To use =mbsync= over a secure connection add
#+begin_example
  SSLType STARTTLS
  SSLVersions TLSv1.2
  CertificateFile ~/.cert/protonmail.crt
#+end_example
to =.mbsyncrc= and put the certificate generated by ~openssl s_client -starttls imap -connect 127.0.0.1:1143 -showcerts~ in =~/.cert/protonmail.crt=, i.e. the lines between (and incluying) =-----BEGIN CERTIFICATE-----= and =-----END CERTIFICATE-----=

Just to make it complete my =.mbsyncrc= file looks as follows
#+begin_src conf :tangle nil
IMAPAccount proton
Host 127.0.0.1
Port 1143
User ohaukeboe@pm.me
SSLType STARTTLS
Pass *****
# CertificateFile /etc/ssl/certs/ca-certificates.crt
CertificateFile ~/.mail/.cert/protonmail.crt

IMAPStore proton-remote
Account proton

MaildirStore proton-local
Subfolders Verbatim
Path ~/.mail/proton/
Inbox ~/.mail/proton/Inbox
Trash ~/.mail/proton/Trash

Channel proton
Far :proton-remote:
Near :proton-local:
Patterns *
Expunge None
CopyArrivalDate yes
Sync All
Create Both
SyncState *
#+end_src
and my =.msmtprc= file looks like:
#+begin_src conf :tangle nil
  # Set default values for all following accounts.
  defaults
  auth           on
  tls            on
  tls_trust_file ~/.mail/.cert/protonmail.crt
  logfile        ~/.msmtp.log

  # Proton
  account        proton
  host           127.0.0.1
  port           1025
  tls_starttls   on
  from           ohaukeboe@pm.me
  user           ohaukeboe@pm.me
  password       *****

  # Set a default account
  account default: proton
#+end_src

#+begin_src elisp
  (use-package mu4e
    :ensure nil
    :defer t
    :if (and (file-exists-p "~/.mail")
             (executable-find "mbsync")
             (executable-find "msmtp")
             (executable-find "mu"))
    ;; :general
    ;; (oh/leader-key
    ;;   "om" '(mu4e :which-key "mu4e"))

    :custom
    (mu4e-split-view nil)
    (mail-user-agent 'mu4e-user-agent)
    (shr-use-colors nil)

    :config
    (setq sendmail-program (executable-find "msmtp")
          send-mail-function 'smtpmail-send-it
          mu4e-root-maildir "~/.mail"

          message-sendmail-f-is-evil t
          message-sendmail-extra-arguments '("--read-envelope-from")
          message-send-mail-function 'message-send-mail-with-sendmail
          message-kill-buffer-on-exit t

          mu4e-get-mail-command (concat (executable-find "mbsync") " -a")
          mu4e-change-filenames-when-moving t

          mu4e-use-fancy-chars t)

    (setq mu4e-contexts
          (list
           ;; (make-mu4e-context
           ;;  :name "ifi"
           ;;  :match-func
           ;;  (lambda (msg)
           ;;    (when msg
           ;;      (string-prefix-p "/ifi" (mu4e-message-field msg :maildir))))
           ;;  :vars '((user-mail-address . "oskah@ifi.uio.no")
           ;;          (user-full-name . "Oskar Haukebøe")
           ;;          (mu4e-sent-folder . "/ifi/Sent Items")
           ;;          (mu4e-trash-folder . "/ifi/Deleted Items")
           ;;          (mu4e-drafts-folder . "/ifi/Drafts")
           ;;          (mu4e-refile-folder . "/ifi/Archive")
           ;;          (smtpmail-smtp-user .)))
           (make-mu4e-context
            :name "proton"
            :match-func
            (lambda (msg)
              (when msg
                (string-prefix-p "/proton" (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "ohaukeboe@pm.me")
                    (user-full-name . "Oskar Haukebøe")
                    (mu4e-sent-folder . "/Sent")
                    (mu4e-trash-folder . "/Trash")
                    (mu4e-drafts-folder . "/Drafts")
                    (mu4e-refile-folder . "/Archive")
                    (smtpmail-smtp-user . "ohaukeboe@pm.me")
                    (mu4e-compose-signature . nil))))))
#+end_src

Org-msg allows for composing the mail using orgmode, and then send it as beautifull html.

#+begin_src elisp
  (use-package org-msg
    :ensure t
      :after mu4e
      :config
      (setq org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \\n:t"
            org-msg-startup "hidestars indent inlineimages"
            org-msg-greeting-fmt "\nHi%s,\n\n"

            org-msg-recipient-names '(("ohaukeboe@pm.me" . "Oskar"))
            org-msg-greeting-name-limit 3
            org-msg-default-alternatives '((new		. (text html))
                                           (reply-to-html	. (text html))
                                           (reply-to-text	. (text)))
            org-msg-convert-citation t
            org-msg-signature "

  Cheers,
  ,#+begin_signature
  Oskar
  ,#+end_signature")
      (org-msg-mode))
#+end_src

#+begin_src elisp
  (use-package mu4e-marker-icons
    :ensure t
    :after mu4e
    :init (mu4e-marker-icons-mode 1))
#+end_src

** Vundo
Not undo-tree

#+begin_src elisp
  (use-package vundo
    :ensure t
    :defer
    :custom
    (vundo-glyph-alist vundo-unicode-symbols)
    (vundo-window-max-height 10))
    ;; :general
    ;; (oh/leader-key
    ;;   "u" '(vundo :wk "not undo tree")))
#+end_src

** Undo-fu
Save & recover undo steps between Emacs sessions.

#+begin_src elisp
  (use-package undo-fu
    :ensure t
    :custom
    (undo-limit (* 64 1024 1024))               ; 64mB.
    (undo-strong-limit (* 96 1024 1024))        ; 96mB.
    (undo-outer-limit (* 10 undo-strong-limit))) ; 960mB.

  (use-package undo-fu-session
    :ensure t
    :config
    (undo-fu-session-global-mode))
#+end_src

** Spell check
This sets up spell-checking using both English and Norwegian dictionaries together. It is also necessary to install =hunspell-en_us= and =hunspell-nb=. Jinx is a much faster alternative to flyspell, and it also supports combining dictionaries.

#+begin_src elisp
  (use-package jinx
    ;; :hook (elpaca-after-init . global-jinx-mode)
    ;;:ensure t
    :after (text-mode prog-mode)
    :custom
    (jinx-languages "en_US nb_NO")

    ;; :general
    ;; (oh/leader-key
    ;;   "sc" '(jinx-correct :wk "correct previous")
    ;;   "ts" '(jinx-mode :wk "toggle spellcheck"))

    :config
    (global-jinx-mode 1)
    (with-eval-after-load 'vertico
      (add-to-list 'vertico-multiform-categories
                   '(jinx grid
                          ;; (:not indexed)
                          (vertico-grid-annotate . 20)))
      (vertico-multiform-mode 1)))
#+end_src

** Thesaurus

#+begin_src elisp
  (use-package powerthesaurus
    :defer
    :ensure t)
    ;; :general
    ;; (oh/leader-key
    ;;   "st" '(powerthesaurus-transient :wk "thesaurus")))
#+end_src

** Helpful
A better help buffer
#+begin_src elisp
  (use-package helpful
    :ensure t
    ;; :custom
    ;; (counsel-describe-function-function #'helpful-callable)
    ;; (counsel-describe-variable-function #'helpful-variable)
    ;; :general
    ;; ('normal "K" 'helpful-at-point)

    ;; (oh/leader-key
    ;;   "hp" 'describe-package
    ;;   "ht" 'describe-theme
    ;;   "hv" 'describe-variable
    ;;   "hf" 'describe-function
    ;;   "hk" 'describe-key)

    :bind
    ([remap describe-function] . helpful-function)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key)
    ([remap describe-command] . helpful-command))
#+end_src

** Devilry
#+begin_src elisp
  (use-package devilry-mode
    :vc (:url "https://github.com/ohaukeboe/devilry-mode")
    :defer
    :custom
    (dm-java-compilation nil))
    ;; :general
    ;; (oh/leader-key
    ;;   "tD" '(devilry-mode :wk "devilry"))
    ;; (oh/leader-key '(devilry-mode-map)
    ;;   "md" '(dm-do-oblig :wk "do oblig")
    ;;   "mc" '(desktop-hard-clear :wk "clear desktop")))
#+end_src

** Olivetti
Make text more readable by narrowing the text at the center of the screen. This is useful for writing prose with visual-line-mode enabled.

#+begin_src elisp
  (use-package olivetti
    :ensure t
    ;; :commands olivetti-mode
    :hook (org-mode . olivetti-mode)
    :custom (olivetti-body-width 90))
    ;; :general
    ;; (oh/leader-key
    ;;   "to" '(olivetti-mode :wk "olivetti")))
#+end_src
