{ pkgs, ... }:
{
  projectRootFile = "flake.nix";
  settings.global.excludes = [
    # Generated by nvfetcher; not hand-formatted.
    "_sources/generated.nix"
  ];

  programs.nixfmt.enable = true;
  programs.shfmt.enable = true;
  programs.toml-sort.enable = true;
}
