{ pkgs, ... }:
{
  projectRootFile = "flake.nix";
  settings.global.excludes = [
    # Generated by nvfetcher; not hand-formatted.
    "_sources/generated.nix"
    # A scaffolding template, not this repo's own config. toml-sort reorders
    # tables and drops comments, which turns secretspec.toml into a trap:
    # [profiles.default] ends up empty at the top and the example declaration
    # below it lands under [providers].
    "workstation/emacs/packages/nix-init-templates/*.toml"
    # Vendored by the Specify CLI and rewritten on every refresh; formatting
    # them here only creates churn on the next `specify` update.
    ".specify/scripts/bash/*.sh"
  ];

  programs.nixfmt.enable = true;
  programs.shfmt.enable = true;
  programs.toml-sort.enable = true;
}
