# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  beads = {
    pname = "beads";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "gastownhall";
      repo = "beads";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-5oDI2MunHrOKx1m5mC0ZaIqZ9+f1YBQotMBUj6U5H1I=";
    };
  };
  caveman-shrink = {
    pname = "caveman-shrink";
    version = "0.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/caveman-shrink/-/caveman-shrink-0.1.0.tgz";
      sha256 = "sha256-K0DszONf6M4UXmwC/gLRkiNatlXLNhQkTKmBiMBPh6c=";
    };
  };
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "1.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-1.6.0.tgz";
      sha256 = "sha256-HmMsLZcUtPgrTPq077nOV1CFx1/+XpdyODEprwEsnIQ=";
    };
  };
  code-review-graph = {
    pname = "code-review-graph";
    version = "v2.3.7";
    src = fetchFromGitHub {
      owner = "tirth8205";
      repo = "code-review-graph";
      rev = "v2.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-xxKEH4JJY2jTNqNSmzkX9D5/7aC+OqhN+rDeb2AO/5c=";
    };
  };
  lsp-ltex-plus = {
    pname = "lsp-ltex-plus";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "emacs-languagetool";
      repo = "lsp-ltex-plus";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-va0+w5ZUiaSASH2JDPRM0R4rwXCnRQKZw62Ftu3Ypfw=";
    };
  };
  pgmacs = {
    pname = "pgmacs";
    version = "v0.42";
    src = fetchFromGitHub {
      owner = "emarsden";
      repo = "pgmacs";
      rev = "v0.42";
      fetchSubmodules = false;
      sha256 = "sha256-AjhtU+YfEeYL/soJTB5o2vHYXyewwtsOoS6oCYnxyF0=";
    };
  };
}
