# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  beads = {
    pname = "beads";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "gastownhall";
      repo = "beads";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-QryUnK04c9Wm9/VgWoaOJW9M2HoZVZzSDMSMBtjKiyc=";
    };
  };
  caveman-shrink = {
    pname = "caveman-shrink";
    version = "0.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/caveman-shrink/-/caveman-shrink-0.1.1.tgz";
      sha256 = "sha256-aQ7biix+i3jBpCCb1fc+hbFP3Fwq1pQ0eauz2dow9ZM=";
    };
  };
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "1.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-1.9.0.tgz";
      sha256 = "sha256-X3U7HL9XdcjkNxE1Is0QwfDO/RZSHgVyVA1XhgVWwTM=";
    };
  };
  code-review-graph = {
    pname = "code-review-graph";
    version = "v2.3.8";
    src = fetchFromGitHub {
      owner = "tirth8205";
      repo = "code-review-graph";
      rev = "v2.3.8";
      fetchSubmodules = false;
      sha256 = "sha256-NhssTYN0McUEpxAlb4bWDrdlCA6jFmXj9Cn9IxdkcUg=";
    };
  };
  lsp-ltex-plus = {
    pname = "lsp-ltex-plus";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "emacs-languagetool";
      repo = "lsp-ltex-plus";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-va0+w5ZUiaSASH2JDPRM0R4rwXCnRQKZw62Ftu3Ypfw=";
    };
  };
  mobile-mcp = {
    pname = "mobile-mcp";
    version = "1.0.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@mobilenext/mobile-mcp/-/mobile-mcp-1.0.4.tgz";
      sha256 = "sha256-aAMy0WTEP+Yh4y7GdSSnasCA0KevVc3363BNFb94JBk=";
    };
  };
  pgmacs = {
    pname = "pgmacs";
    version = "v0.42";
    src = fetchFromGitHub {
      owner = "emarsden";
      repo = "pgmacs";
      rev = "v0.42";
      fetchSubmodules = false;
      sha256 = "sha256-AjhtU+YfEeYL/soJTB5o2vHYXyewwtsOoS6oCYnxyF0=";
    };
  };
}
